# Generated by Django 5.0.7 on 2024-07-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=350)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=200)),
                ('embeddings', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
